---
- name: Install postgresql
  apt: name={{ item }} state=present
  with_items:
    - postgresql-9.3-postgis-2.1
    - libpq-dev
    - python-psycopg2

- name: Start Postgresql Service
  service: name=postgresql state=started enabled=true

- name: Create postgresql user
  sudo_user: postgres
  postgresql_user: name=devmachine password=devmachine role_attr_flags=SUPERUSER

- name: Update postgresql config
  copy: src={{ item }} dest=/etc/postgresql/9.3/main/{{ item }}
  with_items:
    - postgresql.conf
  notify:
    - restart postgresql
