---
- name: My dev machine setup
  hosts: default
  user: vagrant
  sudo: yes

  roles:
    - common
    - mysql 
    - postgresql
    - nodejs
    - mongodb
    - redis
    - memcached
    - docker
    - elasticsearch