---
- name: Add deadsnakes ppa
  apt_repository: repo='ppa:fkrull/deadsnakes'

- name: Update package list
  apt: update_cache=yes

- name: Install python versions
  apt: name={{ item }} state=present
  with_items:
    - python2.6
    - python2.6-dev
    - python3.2
    - python3.2-dev
    - python3.3
    - python3.3-dev
    - python3.4
    - python3.4-dev
