---
- name: Install mysql packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - python-mysqldb

- name: Update Mysql config
  copy: src=my.cnf dest=/etc/mysql/my.cnf
  notify:
    - restart mysql

- name: Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Create mysql user
  mysql_user: name=devmachine password=devmachine priv=*.*:ALL,GRANT host=% state=present
